### ISSUE TITLE
Checkout::Dynamic::Render get the rendered position of the widget

### ISSUE THREAD

**Issue by thanigai-babu17** [Shopify/ui-extensions#475] opened 2022-09-13 15:34 UTC
## If this related to specific APIs or components, please list them here
Checkout::Dynamic::Render

## Is your feature request related to a problem? Please describe.
Is there any way to get the rendered position while using Checkout::Dynamic::Render like Checkout::Dynamic::Render[OrderSummary1].  I have requirement that the view of the extension should change according to the position it was rendered. Right now i dint find any way to determine the position of the widget in API while using dynamic render.

## Additional context
Loom video: [https://www.loom.com/share/421a8f7c341a4c4d871f00a0cc5176af](url)

**Comment by sjanczy2** [comment] 2022-11-01 18:48
Duplicate of #391

**Closed by sjanczy2** 2022-11-01 18:48 UTC
Labels: enhancement
