### ISSUE TITLE
applyDiscountCodeChange returns an error for some customers using accelerated checkout

### ISSUE THREAD

**Issue by ShiriArie** [Shopify/ui-extensions#1511] opened 2023-11-08 07:22 UTC
## Please list the package(s) involved in the issue, and include the version you are using

    "@shopify/app": "3.49.5",
    "@shopify/cli": "3.49.5",
    "@shopify/ui-extensions": "2023.10.0",
    "@shopify/ui-extensions-react": "2023.10.0"

## Describe the bug

We got complaints from some customers getting an error when trying to apply a discount with our checkout extension.
Our extension uses the following Shopify mutation to apply discount codes: useApplyDiscountCodeChange.

We get the following error message from Shopify when trying to use useApplyDiscountCodeChange to apply the discount:
"Could not apply mutation applyDiscountCodeChange: the buyer is using an accelerated wallet"

We could not replicate this behavior but we got reports from several customers about this issue.

## Expected behavior

We expect to be able to apply discount codes regardless of the customers' use in accelerated checkout.

## Screenshots

![image](https://github.com/Shopify/ui-extensions/assets/76816986/e661a39b-48cf-45d6-a410-a7641865a7ef)

![image](https://github.com/Shopify/ui-extensions/assets/76816986/2eb9d0a1-50b9-435e-8fe4-cbb28d6cffca)## Additional context

We recently updated our extension api version to be:
api_version = "2023-10"

Reviewing the 2023-10 documentation for the checkout extension (https://shopify.dev/docs/api/checkout-ui-extensions/2023-10/apis/discounts) reveals the following note:
"This method will return an error if the buyer is using an accelerated checkout method, such as Apple Pay, Google Pay, or Meta Pay."
But this note seems relevant for CheckoutApi - applyDiscountCodeChange and not for useApplyDiscountCodeChange which we use.

<img width="556" alt="image" src="https://github.com/Shopify/ui-extensions/assets/76816986/6125ec2d-363b-442d-bf18-1403671f1729">

**Comment by oreyes1991** [comment] 2024-07-20 15:16
Any luck with this? I'm running into the same issue

**Comment by mleandres** [comment] 2024-08-29 16:09
Hey @edhgoose , this error message is documented below. Is this error message banner being conditionally displayed by your extension? I see this `SetErrorState` line in your extension code:

<img src="https://github.com/user-attachments/assets/e50226ec-88aa-495c-93cd-75c9400c3692" width="500"/>



We don't recommended displaying this message directly to the buyer since it is not localized (See [DiscountCodeChangeResultError on this page](https://shopify.dev/docs/api/checkout-ui-extensions/2023-07/react-hooks/reductions/useapplydiscountcodechange#useApplyDiscountCodeChange))
<img src="https://github.com/user-attachments/assets/20cd7c2b-13c6-4b79-9d2b-f932a240031f" width="500"/>

We've logged being able to Apply Discount Code Changes in accelerated checkouts as a future feature request but this doesn't look like a bug.

**Comment by edhgoose** [comment] 2024-08-29 18:20
Hi @mleandres - I think there's several things in here.

The first is this bug: https://github.com/Shopify/ui-extensions/issues/2133. While we understand that the error message shouldn't be shown, we decided that it was better to show that than nothing.

Now that I've seen a wide range of errors (as documented in the issue), I'd feel more confident in writing a wrapper around your error message that converts it into something friendly for the user that _is_ localised. I just haven't done that yet. Would love your feedback on the other issue as to whether you're likely to add something so we don't need to - as I imagine others would benefit.

The second is:

I understand that you're saying you can't apply discount codes to accelerated payment methods. I assume there's a reason behind this - but for whatever reason it's not supported and that doesn't matter too much. It'd be great if you can tell us why, but I don't see it as being critical.

The thing that's confusing us is that we have _no idea_ how to reproduce this behaviour. As soon as we click to pay with an accelerated payment method, the user is taken out of the Checkout journey into Thank You.

So, how is it possible for a user to be _both_:

a) In the checkout, and able to interact with our extension
b) Using an accelerated payment method?

We'd love reproduction steps on how to achieve this behaviour, so then we can change our UI. And we'd love guidance on how to detect this circumstance - e.g. should we call `applyDiscountCodeChange`, and if it fails with this error, should we change the copy of our modal to say something like: "We can't apply your coupon because you're using an accelerated payment method. Please restart your purchase using your coupon code then choose your payment method"?

I don't think we are seeing this issue for anything other than accelerated payment methods - but without a way to reproduce the case, I don't really know 😢

**Comment by mleandres** [comment] 2024-08-29 18:31
Hey thanks so much for the feedback! We'll definitely take note of that feedback since we're always trying to improve our docs.

As for the accelerated checkout piece, there are some accelerated checkouts that appear "over" our regular checkout such as Google Pay (which appears as a little modal), I think maybe Apple pay does this as well but I'm not sure off the top of my head.

That being said, you _should_ be able to reproduce this with Google Pay, but let us know if you can't get that working.

However, totally agreed that we can do better on documenting error cases.

I'll close this issue but leave the docs suggestions issue open. We do have plans to improve these docs eventually but nothing in the near future.

**Closed by mleandres** 2024-08-29 18:31 UTC
Labels: bug
