### ISSUE TITLE
Checkout app suddenly stopped showing in Checkout and Checkout Editor

### ISSUE THREAD

**Issue by KTruong008** [Shopify/ui-extensions#1151] opened 2023-07-25 16:30 UTC
## Please list the package(s) involved in the issue, and include the version you are using

"@shopify/app": "^3.47.5",
    "@shopify/checkout-ui-extensions-react": "0.27.0",
    "@shopify/cli": "^3.47.5",
    "@shopify/shopify_function": "0.0.3",

## Describe the bug

My app's checkout customizations suddenly stopped appearing in checkout and is not available in the Checkout Editor. All the app blocks I've created have disappeared and I can no longer add the app using the Checkout Editor.

It was just working an hour ago and I haven't made any changes for the past 24 hours. When I try to push a new version it gives this error:

<img width="987" alt="Screen Shot 2023-07-25 at 12 22 48 PM" src="https://github.com/Shopify/ui-extensions/assets/17548405/8c2ce4eb-0226-4583-a80e-1e1864235372">

## Steps to reproduce the behavior:

Not sure

## Expected behavior

1. App blocks should show in Checkout Editor
2. App's customizations should show in Checkout
3. Should be able to create a new version of the extension

**Comment by gil--** [comment] 2023-07-25 16:32
Confirmed. Extensions don't appear to be loading. This is pretty critical given some merchants use extensions for showing required fields. 😟

**Comment by sjanczy2** [comment] 2023-07-25 17:10
Thanks for flagging folks, we're investigating with full priority

**Comment by ndefie** [comment] 2023-07-25 17:10
Confirmed on my end that our production stores are having issues

**Comment by sjanczy2** [comment] 2023-07-25 17:29
Update: We believe we have found the issue and are deploying a fix, I will post again once we've confirmed the fix works.

**Comment by nboliver** [comment] 2023-07-25 21:14
@sjanczy2 Is it possible that the fix for this issue also fixed https://github.com/Shopify/ui-extensions/issues/1139?
I just tested and it appears the `useAttributes` hook is working again, but there has been no communication from Shopify in any of the places that the bug was logged (GitHub, Slack, Plus Support) that the issue was resolved.

**Comment by sjanczy2** [comment] 2023-07-25 22:21
@lporter-extend Feel free to deploy or modify any extensions/profiles if you need to. We are working on a data restore but will need some time, we are accounting for the fact that profiles may have been modified since the incident.

@nboliver This issue should not be related to anything with `useAttributes`, we'll have to follow up on that one separately.

**Comment by gil--** [comment] 2023-07-26 18:41
I know someone else mentioned this but I can't find their post (Maybe it was on Slack) but you can no longer add extensions that rely on the Shipping Address block as it seems to have disappeared from the editor:

![CleanShot 2023-07-26 at 14 38 28](https://github.com/Shopify/ui-extensions/assets/3484527/8be7b4eb-17b1-4641-b211-b5c825ede
![CleanShot 2023-07-26 at 14 38 57](https://github.com/Shopify/ui-extensions/assets/3484527/b22a89dc-3134-4483-9429-fc05b93d8d40)
a99)

**Comment by sjanczy2** [comment] 2023-07-26 19:17
Hi folks, I'm going to post a summary in a separate comment and then close this issue out. I'll open a separate issue for the one flagged above by @gil-- and @nboliver , we are working to deploy the fix for that one as we speak but I think it's worth tracking separately since it the impact is different.

**Comment by sjanczy2** [comment] 2023-07-26 19:17
On July 25, 2023, we were made aware that some merchants encountered issues with the Shopify Checkout editor not displaying extensions for certain stores. At approximately 10:30 AM ET, a change was implemented that resulted in Checkout UI Extensions not appearing in checkout profiles in the checkout editor and checkout buyer experience.

At approximately 3:00 PM ET, the change was reverted for all shops, effectively resolving the issue. At approximately 2:00 AM ET, we confirmed that all impacted extensions were rendering on checkout correctly. This issue is now considered resolved, and the Shopify Checkout Editor is functioning as expected.

**Closed by sjanczy2** 2023-07-26 19:17 UTC
Labels: bug

**Comment by gavinballard** [comment] 2023-07-27 04:10
Thanks for the efforts addressing this @sjanczy2 and @michaelelmgreen!

We are still (at the time of posting) getting intermittent reports from customers of checkout UI extensions not loading, specifically extensions rendering underneath the discount input in the order summary sidebar _on the information step only_ (it's working as normal on the shipping and payment steps).

**Comment by sjanczy2** [comment] 2023-07-27 14:56
@gavinballard I copied that onto a new issue https://github.com/Shopify/ui-extensions/issues/1174, I'll start looking into but please share any details if you can.
