### ISSUE TITLE
Fetch not working for unauthenticated recommendations AJAX API

### ISSUE THREAD

**Issue by KTruong008** [Shopify/ui-extensions#489] opened 2022-09-19 14:25 UTC
## Please list the package(s) involved in the issue, and include the version you are using

"@shopify/checkout-ui-extensions-react": "^0.18.1",
"@shopify/cli": "3.8.0",

## Describe the bug

When using fetch within the checkout ui extension the console returns an error about CORS, preventing apps that use ui extensions from leveraging the product recommendations API.

`Access to fetch at 'https://<shopdomain>/recommendations/products.json?product_id=7800316821723&intent=related' from origin 'https://cdn.shopify.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

Adding the 'no-cors' to the fetch request generates another error, but even if it was resolved would lead to an opaque body that wouldn't return the recommendations within the body.

I've also updated my extension toml to allow network access and have requested and approved access from the partner dashboard for my app. I'm following the docs for using the AJAX API and product recommendations here:

https://shopify.dev/api/ajax
https://shopify.dev/api/ajax/reference/product-recommendations#get-locale-recommendations-products

Also, when I try to access the product/recommendations API through a proxy it gets blocked by password-protected pages, which can't be disabled on dev stores:

<img width="629" alt="checkout-ext-product-block" src="https://user-images.githubusercontent.com/17548405/193855046-89162477-3c8f-462a-a39f-486ce27dfb88.png">

## Steps to reproduce the behavior:

1. Create dev store with extensions preview
2. Create extension
3. Call the recommendation API within extension, using a useEffect hook

```
useEffect(() => {
    const recommendationUrl = 'https://checkout-sales-local.myshopify.com/recommendations/products.json?product_id=${7800316821723}&intent=related';

    fetch(recommendationUrl, {
      method: 'GET',
    })
      .then((response) => response.json())
      .then((data) => {
        console.log('data: ', data);
      });
  }, []);
```

## Expected behavior

The API call will return the recommendations. I thought this would be possible because it notes the AJAX API is an unauthenticated API, and being able to hit the endpoint directly from the extension would be great as the app wouldn't have to depend on non-Shopify infrastructure to fetch recommendations.

Edit: I also tried making the call through an app proxy and was met with the same cors error.

**Comment by bkspace** [comment] 2022-09-29 08:51
Right, have experienced the same issue. From my investigation, I think the issue is two fold:

1.) The recommendations endpoint does not specify a `Access-Control-Allow-Origin` header at all.
2.) 'credentials' is overridden with a value of `omit` on fetch requests inside the worker.

This means that even calling the product endpoint on the AJAX api, which has access control headers, will fail on password protected stores, as it redirects to the /password - I assume because no cookies are passed up with the request (omit).

**Comment by sjanczy2** [comment] 2022-10-18 16:32
Hi folks, a similar question also came up in our discord AMA last week, I can share that answer here.

> We are planning to expand access to the storefront API for checkout extensions, without requiring a public app to become a sales channel
> No specifics on availability yet but we are starting on it soon. In the interim we would probably suggest using metafields if you need to get data into your extension

@KTruong008 I can't really recommend any other specific alternatives because as you've mentioned each of them are really workarounds to the underlying problem of not having access to the storefront API, which is a key capability we are looking to address.

**Comment by jduff** [comment] 2023-03-23 15:24
It looks like this was added to some of the checkout extension apis based on the [change log](https://shopify.dev/docs/apps/checkout#checkout-ui-extensions) via the query object in the [standard API](https://shopify.dev/docs/api/checkout-ui-extensions/extension-points-api#standardapi) are there any plans to add this to the post purchase extensions API as well?

**Comment by sjanczy2** [comment] 2024-03-29 19:57
Going to close this one out, our recommendation is to use the storefront query from within your UI extension (https://shopify.dev/docs/api/checkout-ui-extensions/2024-01/apis/storefront-api), we have no plans to support the AJAX API from checkout UI extensions.

**Closed by sjanczy2** 2024-03-29 19:57 UTC
Labels: enhancement
