### ISSUE TITLE
POS UI Extensions Cart lineItems have stopped being returned correctly (possibly as of 9.16.0)

### ISSUE THREAD

**Issue by derrickrc** [Shopify/ui-extensions#2286] opened 2024-08-21 19:33 UTC
## Please list the package(s) involved in the issue, and include the version you are using

@shopify/retail-ui-extensions-react: "1.3.0"

## Describe the bug

When our app loads, it returns the current line items in the cart. Right now there is buggy behavior where it's not showing all line items in the current cart, but rather a stale / previous cart. It doesn't happen every time, but frequently. We believe this is a new bug as of `9.16.0`.

## Steps to reproduce the behavior:

In debugging, you should be able to reproduce with something like this:

```
  const cart = useCartSubscription();
  const cartItems = cart.lineItems;
React.useEffect(() => {
    api.toast.show(JSON.stringify(cartItems)); // this will sometimes show stale / incorrect data
}, [cartItems]);
```

## Expected behavior

The correct Cart lineItems should be returned

## Screenshots

https://shopifypartners.slack.com/files/U0172NXKTJL/F07HUTN5KA9/microsoftteams-video.mp4
https://shopifypartners.slack.com/files/U0172NXKTJL/F07HUTSCW2Z/img_6696.mov

**Comment by galmis** [comment] 2024-08-23 08:11
I'm also seeing similar (likely the same root cause) issues https://github.com/Shopify/ui-extensions/issues/2299 and suspect other Shopify POS extension developers will notice it soon, too.

**Comment by xqwtsz** [comment] 2024-08-23 09:45
+1

**Comment by NathanJolly** [comment] 2024-08-23 14:01
Thank you for the report. Closing as duplicate to #2299

**Closed by NathanJolly** 2024-08-23 14:01 UTC
Labels: bug
