### ISSUE TITLE
Unable to view the app blocks while previewing the Checkout Profiles

### ISSUE THREAD

**Issue by dani-sanomads** [Shopify/ui-extensions#925] opened 2023-05-09 05:41 UTC
<img width="1144" alt="Screenshot 2023-05-09 at 10 38 43 AM" src="https://user-images.githubusercontent.com/101345208/237003960-77e1c770-28db-4330-991f-b2dfdeb8c7c1.png">
<img width="722" alt="Screenshot 2023-05-09 at 10 40 41 AM" src="https://user-images.githubusercontent.com/101345208/237004200-10538e2b-c02a-4bfc-9cb0-758c6aa18992.png">
<img width="1440" alt="Screenshot 2023-05-09 at 10 41 09 AM" src="https://user-images.githubusercontent.com/101345208/237004268-c211087e-ce0c-465b-b394-bbd08496d316.png">

**Comment by alxclark** [comment] 2023-05-10 16:48
Hi @dani-sanomads, our team fixed the issue for the `initialLoadingFinished`, but we've identified that it wasn't the root cause of extensions not showing in the preview. There is a regression where the preview feature always serves the published checkout profile and we are working on a fix. Apologies for the inconvenience.

**Comment by dani-sanomads** [comment] 2023-05-10 17:54
Hi @alxclark , thanks for the updates.

**Comment by Johnkinging** [comment] 2023-05-12 17:57
This issue should be sorted out now, we identified the regression that was causing it and have it serving the properly associated branding settings and extensions. 

I'm closing this issue as fixed, but please do confirm, and re-open it if you find any further inconsistencies.

Thanks for your patience and for identifying this!

**Closed by Johnkinging** 2023-05-12 17:57 UTC
Labels: bug, Checkout editor

**Comment by dani-sanomads** [comment] 2023-05-12 18:33
Yes, It is working fine. We have checked it. Thanks. @Johnkinging
