### ISSUE TITLE
Using the same app on different checkout steps creates multiple instances of that app

### ISSUE THREAD

**Issue by catalin-invisible** [Shopify/ui-extensions#496] opened 2022-09-20 07:03 UTC
## Describe the bug

Right now, when adding an app in Checkout Editor, it is available to be placed under a single checkout step (Information/Shipping/Payment) when using `Checkout::Dynamic::Render` extension point. If you want to have the same app available under all three checkout pages, then a new app instance has to be added under each page. This creates undesired behavior because each instance has its own independent state. The expectation is to have a single app instance under all steps as opposed to three instances of the same app.

## Steps to reproduce the behavior:

1. go to Checkout Editor
2. go to Information page
3. Add an app
4. Place the app under any section within the Information page and click Save
5. go to Shipping page
6. The app is no longer present to be placed under sections of the Shipping page

## Expected behavior
The app should be available under all pages (checkout steps).

## Screenshots

<img width="1398" alt="image" src="https://user-images.githubusercontent.com/95204557/191188924-d870e742-89e9-489b-b20a-1bfe3bb504ea.png">

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/95204557/191189334-745769af-dd91-4a3f-9be7-fb468acb8f7a.png">

**Comment by stevenou** [comment] 2022-09-20 15:02
I would add that, when you do that, you end up with the extension showing up 3 times in a show when using pages like Shop Pay, each acting independently.

I'm thinking maybe the UI should prevent the user from adding the same extension multiple times on the checkout flow.

**Comment by mollyyingnansun** [comment] 2022-10-03 19:37
Hello folks, this is by design. We want to give the decision of where to add extensions and how to config to merchants. We can close this ticket.

**Closed** 2022-10-04 18:22 UTC
Labels: bug, Checkout editor
