### ISSUE TITLE
App metafields undefined in customer account UI extension

### ISSUE THREAD

**Issue by andrewpye** [Shopify/ui-extensions#1887] opened 2024-04-10 13:36 UTC
## Please list the package(s) involved in the issue, and include the version you are using

@shopify/app: 3.57.1
@shopify/cli: 3.57.1
@shopify/ui-extensions: 2024.1.1
@shopify/ui-extensions-react: 2024.1.1

## Describe the bug
I've built a customer account extension for the `customer-account.profile.block.render` target and am testing it via the CLI's `dev` command. The extension renders fine but if I try accessing `useApi().appMetafields` it returns `undefined`. If I try using `useAppMetafields()` directly, an exception gets thrown within Shopify's code due to the metafields being `undefined`. I know the metafield is populated because I'm able to access it from a checkout UI extension.

## Steps to reproduce the behavior:

1. Scaffold a customer account following the [steps](https://shopify.dev/docs/apps/customer-accounts/build-inline-extensions/order-status?extension=react#create-a-customer-account-ui-extension-for-the-order-status-block-target) from the docs. I then edited mine to 1) remove the full-page extension (it was causing a TypeScript error) and 2) target a block on the profile page. I also added access to the metafield I need in the extension's TOML file. I then tried using both `useApi().appMetafields` and `useAppMetafields()` in the extension and logging the results.
1. Run `yarn dev` and navigate to the test page for the customer account extension.
1. See that the app metafields value is `undefined` when using `useApi().appMetafields`, and that an exception is thrown when using `useAppMetafields()`.

## Expected behavior
App metafields are successfully retrieved without error when using either `useApi().appMetafields` or `useAppMetafields()`.

## Screenshots
N/A

## Additional context
This is my sample extension where I found this issue:

```tsx
import {
  Banner,
  reactExtension,
  useApi,
} from '@shopify/ui-extensions-react/customer-account';
import { RenderExtensionTarget } from '@shopify/ui-extensions/customer-account';

const target = 'customer-account.profile.block.render' as RenderExtensionTarget;

export default reactExtension(target, () => <ProfileExtension />);

function ProfileExtension() {
  const { i18n, extension, appMetafields } = useApi();

  console.log(appMetafields);

  return (
    <Banner
      title={i18n.translate('welcome', { target: extension.target })}
    >
      {`Metafields ${appMetafields ? '' : 'not'} available`}
    </Banner>
  );
}

```

**Comment by andrewpye** [comment] 2024-04-25 08:50
Adding to this: I recently discovered that it's possible to [make GraphQL queries](https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/apis/storefront-api) to the storefront API from within a customer account UI extension. I've verified that this works to retrieve store data (e.g. the store URL, since both `useShop()` nor `useApi().shop` return `undefined` in my profile extension). I figured to try including the metafield I need in the query as well; this works perfectly when making the request via Postman and returns the store URL and my metafield; however, in my profile extension, the metafield comes back as `null`. So, it seems pretty concrete now that metafields cannot be accessed within customer account profile blocks, but it's not clear if this is by design or is a bug – it'd be great to know which, because if it's by design we'll need to look for an alternative way to make data available to our extension.

Also adding a note that I have the metafield I'm attempting to access listed in the extension's `shopify.extension.toml` file like this:

```toml
[[extensions.metafields]]
namespace = "my-namespace"
key = "my-key"
```

so the issue _shouldn't_ be caused by a permissions problem as far as I can tell.

**Comment by lihaokx** [comment] 2024-04-25 18:13
Hi @andrewpye 
Thank you for your ticket.
Sorry for the late response. 

>  So, it seems pretty concrete now that metafields cannot be accessed within customer account profile blocks, but it's not clear if this is by design or is a bug

Yes, it is by design. In customer account ui extension, **appMetafields** and **useAppMetafields** standard APIs are only available on `customer-account.order-status` targets, not be available on other targets, like `customer-account.profile`. You can reference to [the targets for their corresponding available standard api.](https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/targets/profile-(default)/customer-account-profile-addresses-render-after#standardapi)

>  we'll need to look for an alternative way to make data available to our extension.

As you said, you can use customer account api to retrieve metafields, which is also the way we encourage developers to query metafields.

> It also means taking an inconsistent approach between different extensions to achieve the same simple goal, making common code impossible to share between extensions that target different surfaces.

We acknowledge this is not a good experience for developers. We'll revisit our decision to prefer customer account API calls before the release of customer account ui extension to the general public

**Comment by lihaokx** [comment] 2024-04-26 16:44
> We're trying to develop an extension to be ready for customer account extension launch so if the API is going to change that's going to be inconvenient.

API is an ambiguous term. You can use two kinds of APIs to get metafields. 
- Standard js API, like `appMetafields` hook. Only exists on `customer-account.order-status` target now. Whether it will be available on other targets has not been decided yet, unfortunately.
- Customer account graphql API. [Reference](https://shopify.dev/docs/api/customer-account-ui-extensions/unstable/apis/customer-account-api). It is available on all targets, and Metafields query will always be supported on customer account graphql API in the future

In your case, I would suggest to use customer account graphql API, which could always supports metafields query. The code in the query could be wrapped and shared by different components.
Does this make sense to you?

**Comment by lihaokx** [comment] 2024-04-29 15:14
>  It also helps simplify code reuse by having a consistent JS API across different extension surfaces 🙏

I see. We will revisit the decision before launching it to general accessibility.

@andrewpye  Thank you for your info. I will close this one. If you have other questions, feel free to open a new one. 🙇

**Closed by lihaokx** 2024-04-29 15:14 UTC
Labels: bug, Customer account UI extensions

**Comment by andrewpye** [comment] 2024-06-13 13:20
@lihaokx sorry to reopen this, but I'm having difficulties with the GraphQL API. I was able to grab a shop metafield using the sample [above](https://github.com/Shopify/ui-extensions/issues/1887#issuecomment-2076774690). I now need to grab an _app_ metafield. When I use the GraphiQL interface (run `yarn dev` then press `g` once it's running), I'm able to make a query like this:

```graphql
query {
  shop {
    metafield(namespace: "my-namespace", key: "my-key") {
      value
    }
  },
  currentAppInstallation {
    metafields(namespace: "my-namespace", first: 10) {
      nodes {
        key,
        value
      }
    }
  }
}
```

and get a result back that includes both the shop and app metafields. However, when I use the same query in the `customer-account.profile.block.render` extension, I get a `Field 'currentAppInstallation' doesn't exist on type 'QueryRoot'` error. Is there some difference between the GraphQL schema available through GraphiQL and within the customer account UI extensions? Is it documented anywhere? Without being able to access the current app installation within the extension, is there any other way that I can retrieve an app metafield?

**Comment by andrewpye** [comment] 2024-06-13 13:43
> I am wondering how did you create your app metafield definition?

Our app has been using them for some time now, we create them from our back end via the GraphQL API:

```
mutation($metafieldsSetInput: [MetafieldsSetInput!]!) {
  metafieldsSet(metafields: $metafieldsSetInput) {
    metafields {
      id
      namespace
      key
    }
    userErrors {
      field
      message
    }
  }
}
```

These metafields are exactly what is needed to make app blocks conditionally visible ([ref](https://shopify.dev/docs/apps/build/online-store/theme-app-extensions/configuration#conditional-app-blocks)). We're using them for this purpose, and need the same condition available from our customer profile UI extension so that we can provide the same experience for stores using new customer accounts as we currently provide for stores using classic customer accounts. It seems likely that many app developers will have the same idea, so it seems strange to limit the data available to a customer profile UI extension so severely.

Is there any other way at all that I can retrieve an app-data metafield in a customer profile extension?

**Comment by andrewpye** [comment] 2024-06-13 14:57
Thanks for the explanation @lihaokx, and apologies for misunderstanding your original question 🙈 As far as I know we've never explicitly created any metafield definitions – is that something that's new?

>I am not sure what [OwnerType](https://shopify.dev/docs/api/admin-graphql/2024-04/enums/MetafieldOwnerType#top) of your metafields. On customer account API, we only [support this 5 kinds of ownertype.](https://shopify.dev/docs/api/customer/unstable/objects/Metafield#fields), (shop, customer, order, and company and companyLocation)

I'm unfortunately no expert on metafields in the Shopify ecosystem – all I can tell you is that we created the metafields we need following the Shopify documentation for app-data metafields ([ref](https://shopify.dev/docs/apps/build/custom-data/metafields/use-app-data-metafields#step-2-create-an-app-data-metafield)). That seems to suggest that the owner of the metafields is our app installation (we're passing the app installation ID as the `ownerId` on the metafields we're using) – but "app installation" doesn't even seem to appear in the `OwnerType` enum you've linked to here 😅 I'm sure you can appreciate that this is a confusing developer experience since something that's _required_ for functionality to work in one part of an app, doesn't seem to even _exist_ in another closely-related part of the app 😬

**Comment by lihaokx** [comment] 2024-06-13 21:35
Oh. After checking with our team, unfortunately, the app-data metafield is not what is supported on customer account API. And the metafields supported on customer account api [are listed here.](https://shopify.dev/docs/api/customer/unstable/objects/Metafield#fields)

I am seeing there are [some discussion here](https://community.shopify.com/c/extensions/accessing-app-data-metafields-in-checkout-ui-extension/td-p/2453852). Hopefully, it may be helpful.

AFAIK, app-data metafield is used to know how merchant install your app, like app plan. Would you like to specific more context about your use case of app-data metafield on customer account UI extension? So that I can bring back your idea to our team to see how can we support it in the future. Thank you so much. @andrewpye

**Comment by andrewpye** [comment] 2024-06-14 11:51
> app-data metafield is used to know how merchant install your app, like app plan. Would you like to specify more context about your use case of app-data metafield on customer account UI extension?

This is exactly what we're using it for. We currently have an app block which is built for the classic customer account page. It's restricted to merchants that are on a specific plan. We sync that availability to an app-data metafield as a boolean value, and the app block schema allows specifying an app-data metafield that defines whether the block should be available to the merchant. Now that customer account UI extensions are available, we're creating an extension to make this same feature available to merchants using new customer accounts, and as with the app block, the extension should only be available to merchants that are on a specific plan. Unless we're missing something, it isn't possible to make any kind of UI extension (checkout, customer account etc.) available _conditionally_ to merchants – all merchants can see all extensions offered by an app. As a result, we're left to implement the "feature gating" ourselves. Since the feature availability is the same as our existing app block, it made sense to reuse the same flag for our new customer profile UI extension, which is what led to my earlier [question](https://github.com/Shopify/ui-extensions/issues/1887#issuecomment-2165655516). We can retrieve the feature availability from our own API when the extension initialises so we're not blocked here, but it was just a surprise that an app is unable to access its own metafields from within its UI extensions 🤷 Of course, it wouldn't even have been an issue if there were some mechanism available to app developers that allowed them to make UI extensions conditionally visible to merchants like we can do with app blocks...

Out of curiosity, is there a specific reason for app-data metafields not being available in customer account UI extensions?

**Comment by lihaokx** [comment] 2024-06-17 20:52
Thanks for your reply. @andrewpye 

Our team has been aware of this issue. We will revisit the decision to support app-data metafield.

> Out of curiosity, is there a specific reason for app-data metafields not being available in customer account UI extensions?

Because customer account API only support [these kinds of metafields](https://shopify.dev/docs/api/customer/unstable/objects/Metafield#fields), which do not include app-data metafields. I am wondering if you can achieve the same functionality of app-data.metafields by using shop.metafields on customer account API. Here is the idea, creating  a metafield definition when a store is installing your app by admin API, set it access customer_account read. Then, in customer account api, retrieve the metafields. You can reference to [this link](https://shopify.dev/changelog/writing-metafield-values-available-on-the-customer-account-api)

**Comment by andrewpye** [comment] 2024-06-21 07:28
> I am wondering if you can achieve the same functionality of app-data.metafields by using shop.metafields on customer account API. Here is the idea, creating a metafield definition when a store is installing your app by admin API

Thanks for the suggestion @lihaokx! However, we've found syncing data from our system to metafields to occasionally cause problems (data getting out of sync when a metafield create/update operation fails or an operation before we create/update the metafield errors out). Since we already sync this value to one metafield, we don't really want to start syncing it to a _second_ metafield just to workaround a limitation of the platform. Retrieving the value directly from our API via an HTTP request on initialisation works well enough for now.

**Comment by BaggioGiacomo** [comment] 2024-10-03 06:29
Hi guys!

I need to fetch some app data metafields too (metafields with ownerId set to the app id). Will this be added on the customer account API in the future or should I migrate to shop metafields?

Thanks!

**Comment by BaggioGiacomo** [comment] 2024-10-03 15:07
Thanks! @lihaokx 
 
I give you a little bit of context.
I'm the developer behind [Amplius](https://apps.shopify.com/amplius), an app that let the merchants collect additional data that will be saved into metafields.
We also provide a form to put on the account page so the users can update their own additional data (using a theme extension block)
The fields that a user can update are decided by the merchant and saved inside an app-data metafield.
On the theme extension I can get the app metafields just by using `{{ app.metafields.namespace.key.value }}` but on the new customer account page I cannot

Migrating to shop metafields is not a problem for me, I also think it is more correct 👍🏻
