### ISSUE TITLE
Banner Checkout Extension Display None on Mobile

### ISSUE THREAD

**Issue by localoneway** [Shopify/ui-extensions#1674] opened 2024-01-23 00:55 UTC
## Please list the related package(s)

checkout-ui-extensions

## Is your feature request related to a problem? Please describe.

I am trying to have checkout disclaimers in my Checkout and I am using Banners to do it. So far everything works fine, but I am trying to make an option on the client side where if selected, the Banner doe not show up in mobile. I cannot seem to add styling through css or capture screen size. 

## Describe the changes you are looking for

I would like to be able to add classNames to the banner so I can style and use mobile queries. 

## Describe alternatives you’ve considered

I have tried returning Null if clicked which works, but not for specific screens. I want to only hide on mobile. I have also tried to use <View/> but cannot make the banner disappear and cannot target based on screen size.

## Additional context

`import React from "react";
import {
  reactExtension,
  Banner,
  Style,
  View,
  useSettings,
} from "@shopify/ui-extensions-react/checkout";

// Set the entry points for the extension
const checkoutBlock = reactExtension("purchase.checkout.block.render", () => <App />);
export { checkoutBlock };

function App() {

  
  // Use the merchant-defined settings to retrieve the extension's content
  const { title: merchantTitle, description, collapsible, status: merchantStatus, hide_banner, hide_banner_mobile } = useSettings();

  // Set a default status for the banner if a merchant didn't configure the banner in the checkout editor
  const status = merchantStatus ?? 'info';
  const title = merchantTitle ?? 'Custom Banner';

  if (hide_banner_mobile) {
    return null;
  }

  if (hide_banner) {
    return null; // Do not render the banner if hide_banner is true
  }
  

  return (
     <View
     maxInlineSize={Style.default(200)
       .when({viewportInlineSize: {min: 'small'}}, 300)
       .when({viewportInlineSize: {min: 'medium'}}, 400)
       .when({viewportInlineSize: {min: 'large'}}, 800)}
   >
   <Banner title={title} status={status} collapsible={collapsible}>
      {description}
    </Banner>
   </View>
  );
}
`

**Comment by jarthorn** [comment] 2024-04-11 19:23
Duplicate of https://github.com/Shopify/ui-extensions/issues/886. Feedback and usecases welcome there.

**Closed by jarthorn** 2024-04-11 19:23 UTC
Labels: enhancement, UI Components
