### ISSUE TITLE
Checkout UI extension frontend is not loading

### ISSUE THREAD

**Issue by sarveshraj** [Shopify/ui-extensions#804] opened 2023-03-17 15:00 UTC
## Please list the package(s) involved in the issue, and include the version you are using
"@shopify/checkout-ui-extensions-react": "^0.24.0"

## Describe the bug
Extension frontend is not loading. Error:
```
ExtensionTimeoutError: Extension gid://shopify/LocalActivatedExtension/00 timed out while mounting
    at app.esm.en.396224e2c5b14ba9d7a8.js:1:170804
```

## Steps to reproduce the behavior:

1. Create a checkout UI extension
2. Add it on your checkout editor
3. Go to store checkout

## Screenshots

Here is a screenshot of my console.
<img width="1792" alt="Screenshot 2023-03-17 at 8 29 13 PM" src="https://user-images.githubusercontent.com/35839390/225941647-885fa92d-58df-487d-9a4f-7025c8b0967d.png">

## Additional context

The extension render point is `Checkout::Reductions::RenderBefore`

**Comment by jamesvidler** [comment] 2023-03-29 16:45
@sarveshraj it looks like you are getting an error trying to run an extension locally. One way this can happen is if you ran `yarn dev` and then stopped the server. 

You also noted that you added it to your checkout editor. When you are running an extension locally, you do not need to add it to your checkout via the editor. You should be able to run `yarn dev` from within the app and then click the preview link to preview it in your checkout.

**Comment by jamesvidler** [comment] 2023-03-29 20:53
Thanks for the information. The console error you see regarding `gid://shopify/LocalActivatedExtension/00` references a local extension which is trying to load. It is followed by a console message that says your extension threw an error. This likely means there is an error within your extension script. Perhaps you can try troubleshooting by scaffolding a new extension `yarn scaffold extension` in your app and testing that out with the default script?

**Comment by jamesvidler** [comment] 2023-03-30 18:05
Are you able to provide a copy of the extension script which reproduces the problem?

**Comment by jarthorn** [comment] 2023-06-19 14:10
Closing since this is appears to be an issue with your own extension.

**Closed by jarthorn** 2023-06-19 14:10 UTC
Labels: bug, Checkout Production Support, Checkout One, Team - Checkout Extensibility, SEV-5
