### ISSUE TITLE
Checkout UI extension has been executed twice in both editor and actual thank you page

### ISSUE THREAD

**Issue by eric-he-rokt** [Shopify/ui-extensions#1435] opened 2023-10-12 04:41 UTC
## Please list the package(s) involved in the issue, and include the version you are using

 "@shopify/ui-extensions": "2023.10.0",
 "@shopify/ui-extensions-react": "2023.10.0",

## Steps to reproduce the behavior:

1. Code for rendering a simple banner (without useEffect or useState) on the thank you page
```TypeScript
import {
  reactExtension,
  View,
  Banner
} from '@shopify/ui-extensions-react/checkout';
export default reactExtension(
  'purchase.thank-you.block.render',
  () => <Extension />,
);
function Extension() {
  console.log(`render extension at ${Date.now()}`);
  return <View>
    <Banner
      status="critical"
      title="My extension"
    />
  </View>;
}
```
2. Position and save the extension on the thank you page in the editor. UI has only one banner as expected, but we can see `console.log` has been executed twice.
3. The same thing happens on the actual Thank you page.

## Expected behavior

`console.log` should only execute once.

## Screenshots

<img width="386" alt="Screenshot 2023-10-12 at 3 27 23 pm" src="https://github.com/Shopify/ui-extensions/assets/87291804/8b173b2e-28d6-431a-ae8a-ba596ffb80ca">

**Comment by cpeddecord** [comment] 2023-10-26 20:39
Closing this as duplicate of #1006

**Closed by cpeddecord** 2023-10-26 20:39 UTC
Labels: bug
