### ISSUE TITLE
When accepting upsell offer, received an internal error from shopify. 

### ISSUE THREAD

**Issue by jzier3** [Shopify/ui-extensions#459] opened 2022-08-28 13:15 UTC
## Please list the package(s) involved in the issue, and include the version you are using
Using:

    "@shopify/checkout-ui-extensions-react": "^0.18.1",

## Describe the bug

When accepting an upsell (adding item to the current checkout from an extension), we're getting an error in the console: 

```
GraphQL execution failed with errors: [
  {
    "message": "Internal error. Looks like something went wrong on our end.\nRequest ID: 2cc8b2be-7ae8-4fb5-b81a-82da9ec54774 (include this in support requests).",
    "extensions": {
      "code": "INTERNAL_SERVER_ERROR",
      "requestId": "2cc8b2be-7ae8-4fb5-b81a-82da9ec54774"
    }
  }
]
```
## Steps to reproduce the behavior:

1. Add upsell to checkout
2. Accept upsell

## Expected behavior

For product to be added to the cart
## Screenshots
![Screen Shot 2022-08-28 at 4 12 49 PM](https://user-images.githubusercontent.com/71882929/187075810-3e8986a1-2619-4805-b255-8fd314f89e77.png)

## Additional context

Extension with issue: https://partners.shopify.com/941756/apps/7334592513/extensions/checkout_ui_extension/14895120385

**Comment by jzier3** [comment] 2022-08-28 13:16
@kumar303

**Comment by abhisheksingh75** [comment] 2023-05-18 05:55
@lemonmade can you help here? facing same issue :(

**Comment by dnagoda** [comment] 2023-07-11 08:59
@Rafath21 @abhisheksingh75 @jzier3 Closing because we can't reproduce the issue. Please file a new issue if you are still seeing the underlying problem.

**Closed by dnagoda** 2023-07-11 08:59 UTC
Labels: bug
