### ISSUE TITLE
buyerIdentity, useBuyerIdentity, useEmail, and useCustomer are always undefined

### ISSUE THREAD

**Issue by edhgoose** [Shopify/ui-extensions#2068] opened 2024-06-11 21:01 UTC
## Please list the package(s) involved in the issue, and include the version you are using
        "react": "^18.0.0",
        "@shopify/ui-extensions": "2024.1.x",
        "@shopify/ui-extensions-react": "2024.1.x"

## Describe the bug
When making a purchase, the customer must provide email, and potentially provide firstname and surname too.

When using the checkout extensions on the we want to pass details to an API of these customer details.

We're using an app in development, and we have completed the access survey - but do not yet have a published app.

We would expect that the various APIs in the subject would return the details of the customer. However, they all return undefined. This experience seems to be the case for both Thank You and Order Confirmation pages.

We do not receive an exception, which implies that we do have access to the data - but it just isn't defined.

Example code:

```
function Extension() {
	const { buyerIdentity } = useApi();

	console.log("buyerIdentity", buyerIdentity);
	console.log("buyerIdentity.customer", buyerIdentity.customer);

	const cust = useSubscription(buyerIdentity.customer);
	console.log("cust", cust);

	return null;
}

export default reactExtension(
	"customer-account.order-status.block.render",
	() => <Extension />,
);

```

## Steps to reproduce the behavior:

1. Build an extension using the code above
1. Make a purchase on a development store using this extension. Note the payment is with a bogus payment gateway if this is relevant.
1. Note that all of the values for the above logging are undefined.

## Expected behavior

We would expect that all the parameters are at least partially populated.

## Screenshots
Note the parameters have been blurred out, but they are present on the page.
![CleanShot 2024-06-11 at 21 58 43@2x](https://github.com/Shopify/ui-extensions/assets/1108173/5d8066df-0a24-4605-8581-e69df6328fab)

## Additional context

I raised a similar bug at https://github.com/Shopify/ui-extensions/issues/2064, but this looks to be a different issue.

**Comment by edhgoose** [comment] 2024-06-11 22:03
Thanks @jamesvidler - this seems like quite a significant gap for us.

Is there an alternative way to get details of the customer who made a purchase?

For instance, we might want UI that says "Thanks for your order James".

We're looking to make changes on both the thank you and order status pages.

**Comment by edhgoose** [comment] 2024-06-15 09:39
Thanks @jamesvidler, I think I was somehow on an older version of the docs and had missed the billing one.

All good now - thank you.

**Comment by edhgoose** [comment] 2024-07-22 15:28
I've just seen this while paying with Shop Pay. I wonder if that could be the cause? Someone else saw it with Klarna. Is there a documented limitation that these APIs do not work with these accelerated checkout models?

**Comment by edhgoose** [comment] 2024-07-29 22:06
@jaimeBEAM Shopify Support have confirmed they're "actively looking into the issue", but unfortunately can't provide anything further :( 

I've shared your comment with them too.

**Comment by edhgoose** [comment] 2024-08-02 19:16
Hi @mleandres - thank you for the update.

I will check.

In the meantime, I note the [docs](https://shopify.dev/docs/api/checkout-ui-extensions/unstable/apis/buyer-identity#useEmail) say:

> Returns the email address of the buyer that is interacting with the cart. **The value is undefined if the app does not have access to customer data.**

This implies, to me at least, that the value can _only_ be undefined if the app does not have access to customer data.

Is that interpretation incorrect, or is it that the docs don't cover this case because of the issue you've raised internally?

**Comment by mleandres** [comment] 2024-08-02 19:23
> This implies, to me at least, that the value can only be undefined

I believe our intention with that line is "If the app does not have customer data then `undefined` will be returned". I'll relay this feedback to our team since that wording does seem off.

There are some existing cases where `email` being `undefined` is perfectly legitimate (i.e. in guest checkout where an `email` hasn't been entered yet or a customer has decided to use a phone number instead of an email).

**Comment by edhgoose** [comment] 2024-08-02 19:38
Ok. I'd really appreciate if the team could clarify all these cases. We see a similar case with #2138 where values are undefined.

Anyway - back to the issue at hand. I can reliably reproduce the email is undefined @mleandres.

I'd prefer not to upload a video here, because it's for a client's site. I have an open support ticket: 49296700. If I reply there with a video, would that be visible to you?

Regarding the code I'm testing with, it's here: https://github.com/mention-me/ShopifyAppV2/compare/test-for-shop-pay-undefined-email?expand=1

**Comment by edhgoose** [comment] 2024-08-07 16:37
The app I shared the video for is a custom app.

For our 'real' app, we do have the permission.

It does work outside of Shop Pay, so I'd assume it isn't a permissions thing?

**Comment by mleandres** [comment] 2024-08-08 16:11
hey @edhgoose , just wanted to respond before I forget. I still wasn't able to replicate this issue at all but I've put the details up in an issue internally for a deeper investigation so we can prioritize it with other fixes.

**Comment by edhgoose** [comment] 2024-08-17 17:02
Hi @mleandres - any news on this?

Since I wrote the comment above, we've seen about 700 failing requests of the last 18600. That might be only 3-4%, but it's still a significant number to us and our client.

Do you need any more examples?

**Comment by FourSeventy** [comment] 2024-09-04 18:46
I'm having this same exact issue. useEmail() seems to return undefined about 5% of the time with my extension live in production. I know the those customers are filling in their email because of data we collect from a web pixel, so the email exists it's just not being returned by useEmail. @edhgoose Were you able to find any workarounds to this?

**Comment by edhgoose** [comment] 2024-09-04 20:16
@FourSeventy you have no idea how much delight it brings me that someone else is having this issue!!

I was beginning to think I was going insane.

We've found no work around - aside from rolling back to pre Checkout Extensions. We're seeing an almost identical issue at #2280 where some values are also undefined.

The Shopify team have so far been unable to reproduce the error and we can't consistently reproduce it either.

Can I ask some questions to help us all figure it out?

- are you operating across one store/one organisation or across many? We're a provider to many Merchants and we're seeing this issue on many stores.
- are you seeing any other values missing, like order details? Or do you not capture those? If you do use order details, might be worth commenting on #2280 too
- can you share any of the code you're using? For the pixel or the extension? Our extension is open source so it's been useful for the Shopify team to look at.

**Comment by FourSeventy** [comment] 2024-09-08 02:10
We have a widely distributed app across hundreds of Shopify stores. We see it across many of our customers.
We don't capture order details from this extension so we haven't seen that.
The code isn't open source but here is a paired down version of it
```
import {
  useApi,
  reactExtension,
  useAppMetafields,
  InlineStack,
  useEmail,
} from '@shopify/ui-extensions-react/checkout';
import {useCallback, useEffect, useState} from 'react';


const thankYouBlock = reactExtension("purchase.thank-you.block.render", () => <AttributionSurvey />);
export { thankYouBlock };

function AttributionSurvey() {
  const customerEmail = useEmail();
  const {extension, appMetafields, localization, buyerIdentity, shop} = useApi();


  useEffect(() => {
    const fetchData = async () => {

    appMetafields.subscribe((d) => {
      fetch(mySettingsUrl)
        .then(response => {
          if (!response.ok) {
            console.log('Network response was not ok');
          }
          // Parses the response to JSON
          return response.json();
        })
        .then(config => {
          console.log(customerEmail) //undefined sometimes
        });

    };
    fetchData();
  }, []);
  }
}

```

**Comment by edhgoose** [comment] 2024-09-16 22:43
Hi @mleandres - we're still seeing this issue occur in significant volumes. 

We've noticed we're not seeing #2280 anymore, but this issue is continuing. 

Is there any news on your side on resolution?

**Comment by mleandres** [comment] 2024-09-17 13:21
hey @edhgoose and @FourSeventy , Thanks for the extra details! That's all very helpful. We're actively investigating this along with other high priority issues. We don't have an estimate for a fix at the moment but please know that we're working on it.

**Comment by edhgoose** [comment] 2024-09-19 10:01
Hi @mleandres - we've had a client install the app today and they immediately saw examples where email is missing. Interestingly, they were all Klarna purchases.
 
I've shared them with the Shopify support team privately. We seem to have a new ticket - it was originally 49296700 and now it's ticket 50806013.

**Comment by edhgoose** [comment] 2024-09-19 17:26
Hey @mleandres - interestingly, we've finally seen this ourselves!

One of my colleagues was reliably getting this error for a client. I'll share the details in the ticket above privately, but I'll share some details publicly.

We confirmed we were seeing `undefined` in the value for buyerIdentity:

![Image](https://github.com/user-attachments/assets/3952d5ca-7787-4631-8e5e-f21a1f5c253a)

I will ask her to try again tomorrow, and if it still happens, perhaps we can jump on a call together and see if we can debug it together?

**Comment by edhgoose** [comment] 2024-09-24 19:57
Hi @mleandres - is there any news on this issue? Have you and the team been able to reproduce it? 

Is there anything we can do to help?

@FourSeventy curious if you've seen any patterns in your apps?

**Comment by edhgoose** [comment] 2024-10-04 16:57
Out of curiosity, I've added this commit to our code:

https://github.com/mention-me/ShopifyAppV2/commit/538cf2962b683f2eb0b23cd8eda31b7a9f7dcd08

This seems to reliably fire again and again for our clients. I'll leave it running for the weekend to gather a ton of records.

All the other data comes through fine, pointing specifically at useEmail.

**Comment by edhgoose** [comment] 2024-10-07 12:21
@mleandres to provide some additional data - since Friday evening when I added this code (so, approximately 2 1/2 days), we've received 20,000+ instances where the call to `useEmail` returned undefined.

So, 350 an hour ish.

Split across at least 36 stores.

**Comment by edhgoose** [comment] 2024-10-10 22:16
Hi @mleandres,

At least one of the shops we see this on has this setting:

![image001~2.png](https://github.com/user-attachments/assets/58246750-a2e5-420f-bbd0-e3756294270e)

Am I safe in assuming that this is the setting you're referring to, and that with this setting it would be reasonable to assume 100% of transactions should have an email?

Regarding Klarna et al - I'm not sure. I will ask our clients for more examples. One of my colleagues did briefly see this issue, and in that circumstance I believe they were paying with a coupon code which gave them a 100% discount. I do not believe they entered any payment method. I will confirm tomorrow.

**Comment by edhgoose** [comment] 2024-10-11 16:31
Hi @mleandres - @Keng38 and I looked at a random sample of 7 orders made in the last 5 hours across his companies store. All were with Klarna. Does suggest that might be the problem.

**Comment by edhgoose** [comment] 2024-10-24 18:27
Hey @mleandres - is there any update on this?

It's a P1 issue for us, and we really need a resolution! We're still getting thousands of instances of this a day. Is there anything further we can do to help you and the team track this down?

**Comment by edhgoose** [comment] 2024-11-05 15:22
Hi @mleandres - any word? Like I say, P1 issue. We need this resolved. We've had another client complain today.

**Comment by dnagoda** [comment] 2024-11-14 15:10
Thanks @edhgoose . Very interested in what you see after you deploy the change.

> would you not expect that we'd see two requests to our API from this code - one with no email, and then when the email eventually appears

The `useEmail` is async, although it's hard to see that because of the hook. In most cases the email value will be available immediately, but with all things async, there's some set of cases where the value won't be available immediately, hence the `undefined`.

Unfortunately, we still haven't been able to replicate this issue in test environments or live. That makes root causing the issue problematic because ultimately the expected values are recorded in the order. Have you been able to replicate this on a test shop?

**Comment by edgardcooper-thomasdhondt** [comment] 2024-11-15 10:33
Hello, we are experiencing the same issue in the following case:
- If we use a Shopify Pay payment method, the email is available on the thank you page via the `useEmail` hook
- If we use an external payment method (Mollie in our case), the email will always be undefined via the `useEmail` hook.

**Comment by dnagoda** [comment] 2024-11-18 16:35
@edhgoose Thanks for the testing information.

> Is that documented anywhere?

Most of the values accessible using the extension APIs are `StatefulRemoteSubscribable`s. You can see that for the BuyerIdentity API here: https://shopify.dev/docs/api/checkout-ui-extensions/unstable/apis/buyer-identity

When you access these values using a hook like `useEmail` that's mostly hidden from you by the hook, which subscribes to the value for you.

Good news. We've got a code fix in review. Long story short, we found some guest checkout flows where the customer information available on the Thank You Page became stale and unavailable.

We still haven't been able to replicate the issue in non-guest checkouts. In all cases for non-guest checkouts, we're seeing the expected data available.

**Comment by edhgoose** [comment] 2024-11-18 17:20
Hi @dnagoda,

That's excellent news. I appreciate you're probably busy, but if there's an opportunity to know the "long story" version just to shed a bit more light on it? I'd be delightfully curious. 

Do you have an estimated time of when the fix might be deployed too?

Regarding the testing we've done - I noticed a bug in our implementation and have deployed some code changes subsequently. So discard those numbers above.

A rough guide on the numbers should be:

- Around 3.5k to 5k an hour did not receive an email
- Around 600 per hour eventually do repopulate the email

There's still an interesting discrepancy between those numbers.

I suggest I'll leave everything as is until your fix is deployed, then we can try removing the debug code and getting a report on how many transactions are working.

🤞 that we're on the home straight now.

**Comment by edhgoose** [comment] 2024-11-20 18:05
Hey @dnagoda 

Thanks! I'll take a look.

Can I confirm something like Klarna would be an offsite payment gateway?

We believe we saw the issue for mostly guest checkouts, using services like Klarna.

We don't mind about the no-email case (our clients exclusively use email).

**Comment by dnagoda** [comment] 2024-11-20 22:06
That's great news. Thanks again for all the communication back and forth to finally get to a solution. Closing the issue.

**Comment by edgardcooper-thomasdhondt** [comment] 2024-11-20 22:07
@dnagoda I can confirm that it fixed the issue we were experiencing. Thanks!

**Closed by dnagoda** 2024-11-20 22:06 UTC
Labels: bug, Checkout UI Extensions

**Comment by dnagoda** [comment] 2024-11-20 22:08
@edgardcooper-thomasdhondt Thanks for confirming.

**Comment by edhgoose** [comment] 2024-11-21 12:51
Confirming further - we have had no incidents of missing emails since yesterday.

Thanks a million @dnagoda, @mleandres - and thanks to all the team involved.

I appreciate you're busy - but I would love to know if there's:

a) Anything which could have expedited the resolution of this? I appreciate we both found it very difficult to reproduce and that would have made it easier, but was there anything in your discovery of the fix which now you know about which could have helped us?

b) I'd love to know more about what exactly the problem was. I appreciate it's probably some deep oddity in your platform that either you can't share or won't mean much without context, but given I've been absolutely desperate to chase this down for ~6 months, I would love the closure ❤

**Comment by dnagoda** [comment] 2024-11-25 20:00
Without getting into too much detail, the main issue here was that we couldn't reproduce the issue. We've recently (not in time for this issue) introduced some new internal tooling that should help root cause hard to reproduce issues like this. Hopefully that reduces the number of long fix times lines like the one.
