### ISSUE TITLE
[Checkout Extension] Order Metafields not updating consistently

### ISSUE THREAD

**Issue by ctrlaltdylan** [Shopify/ui-extensions#1912] opened 2024-04-26 14:30 UTC
## Please list the package(s) involved in the issue, and include the version you are using

```
    "@shopify/ui-extensions": "2024.1.x",
    "@shopify/ui-extensions-react": "2024.1.x",
```

## Describe the bug

Hello,

We've noticed a bug with attempting to apply order metafields in Checkout UI Extensions.

Applying a metafield change during checkout where a metafield value is already present will result in a false positive result.

Here's a snippet of example code:

```javascript
applyMetafieldsChange({
  type: "updateMetafield",
  key: "check_id",
  namespace: "real_id",
  value: check.id,
  valueType: "string",
})
.then(() => {
  console.log("Updated real_id.check_id metafield to : ", check.id);
  console.log(
  "Result: ",
  metafields.find((mf) => mf.key == "check_id")?.value
  );
})
.catch((e) => {
  console.error(`Failed to update metafield`);
  console.error(e);
});
```

If `check_id` in this example is `bbbbbbb` for example, then you'd expect the result to be `bbbbbbb`. Yet, we're seeing this strange output from this code above:

```
Updated real_id.check_id metafield to : bbbbbbb
Result: aaaaaaa
```
It appears the `applyMetafieldsChange` doesn't actually properly update the metafield nor does it throw an error in this case when the update failed.

Is there a special flag that needs to be passed to "force" an update?

## Steps to reproduce the behavior:

1. Scaffold a checkout extensions
1. Update a order metafield with `applyMetafieldUpdate`
1. Observe succesful change
1. Attempt to update the same metafield again with a different value
1. Observe a result that's claiming to be sucessful, yet you'll see an old value

## Expected behavior

I expect `applyMetafieldUpdate` to apply the newest value sychronously.

**Comment by jamesvidler** [comment] 2024-05-07 20:35
@ctrlaltdylan I reproduced the issue you reported, however the metafields do in-fact change. The issue I think you are running into is the the `metafields` value you are console logging has not changed immediately. That's because metafield changes cause a "state" update to occur and you are checking for the value before it has updated.

Consider this example:
```javascript
import React, { useEffect } from "react";
import {
  Button,
  useApi,
  useMetafields,
} from "@shopify/ui-extensions-react/checkout";

export default function App() {
  const { applyMetafieldChange } = useApi("purchase.checkout.block.render");

  // The useMetafields hook will re-render your component because it has changed AFTER your applyMetafieldChange
  const metafields = useMetafields();

  
  // This console.log will have the appropriate value logged
  console.log(metafields);

  function doThing() {
    const updatedValue: string = Date.now().toLocaleString();
    applyMetafieldChange({
      type: "updateMetafield",
      key: "check_id",
      namespace: "real_id",
      value: updatedValue,
      valueType: "string",
    })
      .then(() => {
        console.log("Updated real_id.check_id metafield to : ", updatedValue);
       // This console.log will return a stale value, because the React component hasn't re-rendered yet with the new value
        console.log(
          "Result: ",
          metafields.find((mf) => mf.key == "check_id")?.value
        );
      })
      .catch((e) => {
        console.error(`Failed to update metafield`);
        console.error(e);
      });
  }

  return <Button onPress={doThing}>Do thing</Button>;
}
```

**Comment by jamesvidler** [comment] 2024-05-24 21:49
Closing this issue, but please feel free to re-open it if you still encounter this issue.

**Closed by jamesvidler** 2024-05-24 21:49 UTC
Labels: bug
