### ISSUE TITLE
Checkout UI extensions DatePicker component selects yesterday's date

### ISSUE THREAD

**Issue by davidpaulsson** [Shopify/ui-extensions#906] opened 2023-04-27 11:29 UTC
## Please list the package(s) involved in the issue, and include the version you are using

@shopify/checkout-ui-extensions-react: 0.26.0

## Describe the bug

When the week starts on Monday, click on a date will select yesterday's date.

## Steps to reproduce the behavior:

Be on a locale where weeks go from Monday to Sunday. Use the DatePicker component. Click a date, for example, 2023-04-15, and the value passed from the `onChange` handler will be 2023-04-14.

## Expected behavior

The date clicked should set the date clicked, not yesterday's date.

## Screenshots

![2023-04-27 at 13 16 44 - Teal Gayal](https://user-images.githubusercontent.com/779321/234848196-4dabe143-0f41-4b17-8b57-1021a14f9d36.gif)

## Additional context

Not strictly related to this ticket, but will you be able to add the same props as you have on the [Polaris Datepicker](https://polaris.shopify.com/components/selection-and-input/date-picker)? I'm specifically looking for `disableDatesBefore` and `disableDatesAfter`. And maybe `weekStartsOn` as that seems related to this ticket ;)

**Comment by igor10k** [comment] 2023-04-27 20:50
@davidpaulsson thanks for bringing that up! Will you please provide a code snippet that causes the issue? Unfortunately I can't reproduce it so far.

> Not strictly related to this ticket, but will you be able to add the same props as you have on the [Polaris Datepicker](https://polaris.shopify.com/components/selection-and-input/date-picker)? I'm specifically looking for disableDatesBefore and disableDatesAfter.

That is currently available just with a different API.

`disableDatesBefore={new Date('Sat Feb 03 2018 00:00:00 GMT-0500 (EST)')}` alternative:

```tsx
<DatePicker
  ...
  disabled={[{end: '2018-02-02'}]}
/>
```

`disableDatesAfter={new Date('Sun Feb 18 2018 00:00:00 GMT-0500 (EST)')}` alternative:

```tsx
<DatePicker
  ...
  disabled={[{start: '2018-02-19'}]}
/>
```

> And maybe weekStartsOn as that seems related to this ticket ;)

We don't currently have plans to expose such property because of the localization issues such API could bring. We believe that a date picker should adapt to the person using it.

**Comment by davidpaulsson** [comment] 2023-04-28 07:09
Also found that while the `disabled` prop renders the dates as disabled/grayed-out, they're still clickable and fire the `onChange` event handler with the disabled date as the passed value. I can ofc prevent setting the selected date in the `onChange` event handler myself, but not sure if it's the intended behavior that the disabled/grayed-out dates should be clickable at all.

**Comment by igor10k** [comment] 2023-04-28 22:10
@davidpaulsson thanks a lot for the code and the screencasts! Both were super helpful!

And both issues you reported should now be fixed. No changes are required from your side. Disabled dates of course should not be clickable, `onChange` should not be called, thanks for reporting that as well!

I'm closing this issue but feel free to reopen if selecting dates doesn't work as expected. Also, if you notice anything else that doesn't seem right don't hesitate to create a new github issue.

**Closed by igor10k** 2023-04-28 22:10 UTC
Labels: bug
