### ISSUE TITLE
[Checkout UI] useApplyShippingAddressChange doesn't update address1 for Spain addresses

### ISSUE THREAD

**Issue by emelerofik** [Shopify/ui-extensions#2102] opened 2024-06-19 09:31 UTC
## Please list the package(s) involved in the issue, and include the version you are using

"@shopify/ui-extensions": "2024.4.x",
"@shopify/ui-extensions-react": "2024.4.x",
"react": "^18.0.0"

## Describe the bug

Since two days ago, our Checkout UI Extension can't update the address1 value from the checkout address form. It seems to be realated to spanish addresses, it's working on other countries (ex. Canada, Australia, United Kingdom, Switzerland...).

## Steps to reproduce the behavior:

1. useApplyShippingAddressChange with a spanish address
2. Hook is returning: `AddressApiError: Enter an address`

## Expected behavior

`address1` should be updated

## Screenshots

<img width="704" alt="image" src="https://github.com/Shopify/ui-extensions/assets/139156805/a8989eb7-db17-470d-b260-c1749de59661">
<img width="513" alt="image" src="https://github.com/Shopify/ui-extensions/assets/139156805/3b215c0f-242b-48f6-9ffa-3ef5d727a22f">

## Additional context

We tested the following package versions:
- 2024.4.x
- 2024.1.x
- 2023.10.2

**Comment by jamesvidler** [comment] 2024-06-21 16:23
Closing as a duplicate of https://github.com/Shopify/ui-extensions/issues/2102 (resolved).

**Closed by jamesvidler** 2024-06-21 16:23 UTC
Labels: bug
